In [4]:
import numpy as np

In [6]:
A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])
print(A + 1)
print(list(map(lambda x:x+1, A)))
print([x+1 for x in A])


[ 3  1  2 10  2  2  2  1  4  6]
[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]
[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]


In [12]:
a = np.arange(22,71,2)
print(a)
b = np.arange(21,72,2)
print(b)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68
 70]
[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


In [16]:
height = [1,2,3,4,5]
delta = [1,2,3,4,5]

def update_height1(height,delta):

    height = np.array(height)
    delta = np.array(delta)
    new_height1 = height+delta 

    return new_height1

print(update_height1(height,delta))

def update_height2(height, delta):

    new_height2=[]

    for i in range(len(height)):

        new_height2.append(height[i]+delta[i])

    return new_height2

print(update_height2(height,delta))

[ 2  4  6  8 10]
[2, 4, 6, 8, 10]


In [18]:
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [17]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [28]:
A = [1,1,2,2,4]
B = [0.6,1.29,1.99,2.69,3.4]

def mse(A,B):
    '''A,B -> Numpy arrays
       output -> A float rounded up to 2 decimal points should be returned'''
    
    ### STEP 1. Calculate difference between elements of A and B
    # A = np.array(A)
    # B = np.array(B)
    diff = np.subtract(A,B)
    
    ## STEP 2: Take square of difference
    
    sq_diff = np.square(diff)
    
    ## STEP3 : Take mean of squared difference
    
    mean_sq_diff = np.mean(sq_diff)
    
    ## STEP 4 : Round off values to 2 decimal places.
    
    mean_sq_diff = np.round(mean_sq_diff, decimals = 2)
    
    return mean_sq_diff

mse(A,B)

0.22

In [29]:
9.5/2

4.75

In [55]:
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])

#mask = birds == 'Cranes'
mask = np.where(birds=='Cranes')

(array([5, 8]),)

In [57]:
#age[mask * age > 0]
age[mask]

array([4. , 5.5])

In [51]:
#cranes_age = age[mask * age > 0]
cranes_age = age[mask]

In [54]:
np.round(np.mean(cranes_age),2)

4.75

# AirBNB NPS

In [60]:
score = np.loadtxt('survey.txt', dtype = 'int')

In [61]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [62]:
score.shape

(1167,)

In [64]:
score.min()

1

In [65]:
score.max()

10

Looks like, there are no records with 0 score.

Now, let's calculate NPS using these response.

NPS = % Promoters - % Detractors

Now, in order to calculate NPS, we need to calculate two things:

% Promoters
% Detractors
In order to calculate % Promoters and % Detractors, we need to get the count of promoter as well as detractor.

Question: How can we get the count of Promoter/ Detractor ?
We can do so by using fancy indexing (masking )

### Detractors have a score <=6

In [75]:
# print(score[score <= 6])
# print(score[score <= 6].shape)
# print(score[score <= 6].shape[0])

detractors = score[score <= 6].shape[0]
total = score.shape[0]
percent_detractors = detractors/total*100
percent_detractors


28.449014567266495

### Similarly, Promoters have a score 9-10

In [76]:
promoters = score[score >= 9].shape[0]
percent_promoters = promoters/total*100
percent_promoters

52.185089974293064

### For calculating NPS, we need to

% promoters - % detractors

In [77]:
nps = percent_promoters - percent_detractors
np.round(nps)

24.0