In [2]:
import numpy as np

# Q1. Rotate the array

Given an array in form of a matrix of size (n, n), rotate the matrix clockwise by 90º.

> Input Format: A 2d numpy array

> Output Format: A 2d numpy array

> Sample Input:
```
[[1 2 3] 
 [4 5 6]
 [7 8 9]]
```

> Sample Output:
```
[[7 4 1]
 [8 5 2]
 [9 6 3]]
```

Note: Try Transpose / reversing.

In [2]:
mat = np.arange(1,10).reshape(3,3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
mat.T[:, ::-1]

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [20]:
import numpy as np
def rotate_img(mat):
    '''mat -> A 2d numpy array
       output -> A 2d numpy array is expected to be returned'''

    # YOUR CODE GOES HERE
    print(mat.T[:, ::-1])

# Q2. Sort the birds

> Problem Description: Given a list of birds and their corresponding age, return the name of birds sorted according to age (ascending)

> Input Format: Two 1D array list i.e. bird array and age array

> Output Format: A 1D array

> Sample Input:
```
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]
```

> Sample Output:
```
['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'spoonbills', 'Cranes', 'plovers', 'spoonbills']
```

Side Note: Recall the functionality of .sort() and .argsort()

In [17]:
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])
print(birds)
print(age)

['spoonbills' 'plovers' 'plovers' 'plovers' 'plovers' 'Cranes' 'plovers'
 'plovers' 'Cranes' 'spoonbills']
[5.5 6.  3.5 1.5 3.  4.  3.5 2.  5.5 6. ]


In [18]:
np.argsort(age)

array([3, 7, 4, 2, 6, 5, 0, 8, 1, 9])

In [19]:
birds[np.argsort(age)]

array(['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes',
       'spoonbills', 'Cranes', 'plovers', 'spoonbills'], dtype='<U10')

In [21]:
import numpy as np

def sort_birds(birds, age):
    '''
    INPUT: birds, age -> 1D numpy array
    
    OUTPUT: result -> sorted bird 1D array
    '''
    
    ## STEP 1 : Get the sorted index of age.
    
    sorted_age_index = np.argsort(age)
    
    ## STEP 2: Use the index from previous step to get sorted birds
    
    result = birds[sorted_age_index]
    
    return result

# Q3. 2D indexing and slicing

> Problem Description: Given a M x N array, Perform the following operations:
> 1. Get the odd rows from the array i.e. 1st, 3rd, 5th etc..
> 2. Convert the above result into 1D array and return it.

> Input Format: A 2D numpy array

> Output Format: A 1D numpy array

> Sample Input:
```
[[1, 2, 3] 
 [4, 5, 6]
 [7, 8, 9]]
```

> Sample Output:
```
[1, 2, 3, 7, 8, 9]
```

In [22]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
odd_row_array = arr[::2]
odd_row_array

array([[1, 2, 3],
       [7, 8, 9]])

In [25]:
odd_row_array.flatten()

array([1, 2, 3, 7, 8, 9])

In [26]:
import numpy as np
def indexing(arr):
    '''
    INPUT: 
    arr -> 2D array of shape M x N
    
    OUTPUT: 
    result -> 1D array
    '''
    
    result = None
    
    
    ## Step 1: Get the odd rows from the array
    
    odd_row_array = arr[::2]
    
    
    ## Step 2: Convert it to 1D array
    
    result = odd_row_array.flatten()
    
    
    ## YOUR CODE ENDS HERE. MAY THE FORCE BE WITH YOU.
    
    return result

# Q4. Numpy on 2D

Given the 2-D array X,
```
import numpy as np
X = np.arange(12).reshape(3,4)
```
So, X is
```
[[ 0 1 2 3] 
 [ 4 5 6 7]
 [ 8 9 10 11]]
```
Which of the following is/are true statements.

In [40]:
X = np.arange(12).reshape(3,4)
print(X.max(axis=1))
#X.sum()
print(X.T, X.T.max(axis=0))
print([i.min() for i in X])

[ 3  7 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] [ 3  7 11]
[0, 4, 8]


# Q5. What about code?
```
import numpy as np
arr = 2*np.arange(0,2,0.5)
if arr <= 0.6:
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy") 
```
In the above code, 'condition' implies the situation that arr has at least one value smaller than or equal to 0.6. Which option is true wrt the code and condition?

In [43]:
arr = 2*np.arange(0,2,0.5)
if arr <= 0.6:
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [42]:
arr

array([0., 1., 2., 3.])

In [45]:
arr.any() <= 0.6

False

In [49]:
arr.all() <= 0.6

True

> # The Code will throw ValueError, and np.any() should be used to get the required output.

# Q6. Sorting in matrix


You are a Teaching Assistant of the DSML course. You have access to every student’s marks in every quiz. The marks are stored in a matrix where matrix[i][j] represents the marks of the ith student in the jth quiz.

The course instructor wants you to sort the marks of students according to jth quiz in increasing order so that he can evaluate the performance of students in that particular quiz.

Here, you have to create a python program using which the instructor can sort the data on the basis of a given column(quiz). The program will return the matrix with the marks sorted in jth quiz.

The dimension of the input matrix is m× n, the output is expected to be a 2d numpy matrix of dimension mxn, but in the output the jth column must be arranged in the ascending order.

> Note: The input will be 2D list not array. First convert it to array.

> Input Format: Number of test cases
> For each test case, number of rows for matrix and the column to be sorted in a new line.
> For each row in matrix, space separated integers are taken as input in a new line.

> Output Format: The 2D matrix, or each row in matrix space separated integers

> Sample Input:
```
1
3 2 
5 3 9
2 1 4
7 6 8
```

> Sample Output:
```
[[2 1 4]
 [5 3 9]
 [7 6 8]]
```

> Explanation: The 2nd column of the matrix is [3, 1, 6], the column after sorting becomes [1, 3, 6].

> ***Note: While sorting the marks, take care of rearranging the relative order of rows too. As, [2 1 4] is a row at index 1 in the original matrix, but after sorting the 2nd column, we had to rearrange its order as mentioned in the sample output.***

In [5]:
list2d = np.array([[5,3,9],
                   [2,1,4],
                   [7,6,8]])
j = 3
list2d

array([[5, 3, 9],
       [2, 1, 4],
       [7, 6, 8]])

In [7]:
sort_col = list2d[:, j-1]
sort_col_index = np.argsort(sort_col)
list2d[sort_col_index]

array([[2, 1, 4],
       [5, 3, 9],
       [7, 6, 8]])

In [8]:
import numpy as np
def sort_marks(list2d, j):
    '''Input: arr2d= a 2d python list.
       j= integer representing the number of quiz according to which the marks need to be sorted.
       Output: a 2d numpy array.'''
    list2d = np.array(list2d)
    sort_col = list2d[:, j-1]
    sort_col_index = np.argsort(sort_col)

    ans = list2d[sort_col_index]
    # YOUR CODE GOES HERE
    
    return ans
    